### ISSUE TITLE
It should be possible to overwrite any existing meta tags

### ISSUE THREAD

**Issue by juho-jaakkola** [vuestorefront/vue-storefront#3751]
## Current behavior
I am trying to change the value of this `robots` meta tag from my custom component:

```
<meta data-vue-meta="true" name="robots" content="index, follow">
```

My goal is to _modify_ the existing tag. However, what happens is, that a second tag gets added instead:

```
<meta data-vue-meta="true" name="robots" content="index, follow">
<meta data-vue-meta="true" name="robots" content="index, no-follow">
```

## Expected behavior
Developers should be able to decide whether they want to add a new tag, or overwrite the value of an existing one.

This can be achieved by adding the `vmid` property to each tag: https://vue-meta.nuxtjs.org/api/#tagidkeyname

The `description` meta tag already has the `vmid="description"` property: https://github.com/DivanteLtd/vue-storefront/blob/v1.10.3/src/themes/default/head.js#L9 

I don't know why it hasn't been added to the others.

Are there any potential drawbacks of adding `vmid` to all of them?

## Repository
https://github.com/DivanteLtd/vue-storefront/tree/v1.10.3

## Can you handle fixing this bug by yourself?
* [x] YES, if someone confirms the correct action
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by juho-jaakkola** [comment]
I can work on this if someone confirms whether it is ok to add the `vmid` property to all of the meta tags.

**Comment by juho-jaakkola** [comment]
I suppose this only needs to be implemented to VSF 2, because in version 1 site owners override the whole theme, so it is easy to just make the needed changes into the custom theme.

However in VSF 2 it will be possible to extend the default theme by overriding only individuak parts of it. So this should be implemented at least there.
