### ISSUE TITLE
State field refactor

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#5618]
## Current behavior

Using State field during checkout returns GraphQL errors because no state is added to our commercetools

## Expected behavior

State field is a select. States are predefined in the config and taxes for them are prepared on CT.

### TODO
* [x] Select field on the checkout shipping
* [x] Select field on the checkout billing
* [x] Use values from config on 2 above, MyAccount Shipping, MyAccount Billing 
* [x] Nice error showing (current one is ugly for select fields)
* [ ] Unify view on Checkout and MyAccount (let's move it to a different task, too much stuff for one)

## Steps to reproduce the issue

1. Add smth to the cart
1. Open checkout
1. Provide some value to State field
1. Errors appears

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.
