### ISSUE TITLE
Port phoneNum validator to the develop

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#5730]
## Todo

- [x] Close this one: https://github.com/vuestorefront/vsf-default/pull/62
- [x] Remove `phoneNum` from `1.12.3`: https://github.com/vuestorefront/vue-storefront/blob/hotfix/v1.12.3/core/helpers/validators/index.ts
- [x] Add `phoneNum` to the `develop`: https://github.com/vuestorefront/vue-storefront/blob/develop/core/helpers/validators/index.ts
- [x] Add unit tests for phoneNum to the develop

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by lukaszjedrasik** [comment]
- Removed `phoneNum` from `1.12.3`: https://github.com/vuestorefront/vue-storefront/pull/5736
- Added `phoneNum` to the `develop` + unit tests: https://github.com/vuestorefront/vue-storefront/pull/5737
